config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index"
  resources "todos"
  resources "users"
  get "/signin" => "sessions#new", as: :new_signin
  post "/signin" => "sessions#create", as: :signin
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, :due_date, presence: true
  belongs_to :user
  # ------------------ FILTER METHODS -----------------------
  # 1. overdue
  # 2. due_today
  # 3. due_later
  scope :overdue, -> { where("due_date < ?", Date.today) }
  scope :due_today, -> { where("due_date = ?", Date.today) }
  scope :due_later, -> { where("due_date > ?", Date.today) }

  def self.completed(status)
    where(completed: status)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :email, presence: true
  has_secure_password
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    if @current_user
      return @current_user
    end
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index", locals: { current_user: current_user }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "new"
  end

  def create
    user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password])
      session[:current_user_id] = user.id
      current_user
      redirect_to "/"
    else
      flash[:error] = "Invalid credentials"
      redirect_to new_signin_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    if current_user
      render "index"
    else
      redirect_to "/"
    end
  end

  def create
    if not current_user
      render plain: "Please login first"
      return
    end
    todo_text = params[:todo_text]
    due_date = DateTime.parse(params[:due_date])
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    if not new_todo.save
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    else
      redirect_to todos_path
    end
  end

  def update
    if not current_user
      render plain: "Please login first"
    end
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    if not current_user
      render plain: "Please login first"
    end
    id = params[:id]
    current_user.todos.find(id).destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def create
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    password = params[:password]
    new_user = User.new(
      first_name: first_name,
      last_name: last_name,
      email: email,
      password: password,
    )
    if not new_user.save
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to new_user_path
    else
      session[:current_user_id] = new_user.id
      @current_user = current_user
      redirect_to "/"
    end
  end

  def new
    render "users/new"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section class="body__main--root">
  <h1 class="main__h1--app-head">Welcome to Todo Manager</h1>
  <p class="ul__li--todo">If you are new user, <a href="/users/new">sign up here</a></p>
  <p class="ul__li--todo">If you are old user, <a href="/signin">sigin here</a></p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo Manager App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <h1 align="left" class="body__main--root main__h1--app-head welcome_user">
          Welcome <%= @current_user.first_name %>!
          <%= link_to "Sign out!", destroy_session_path, method: "delete", class: "signout" %>
      </h1>
    <% end %>

    <% if flash[:error] %>
      <p class="body__section--root error"> <%= flash[:error] %> </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todos-section.html.erb
<section>
    <div class="block--flex block--pad">
      <h3 class="due-head"><%= title %></h3>
      <p class="overdue-dones--info">
        <%= todos.completed(true).count %> / <%= todos.count %>
      </p>
    </div>
    <ul>
      <% todos.each do |todo| %>

        <li class="ul__li--todo block--flex">

          <%= form_with(url: "/todos/#{todo.id}", method: "patch") do |form| %>
            <%= form.check_box :completed ,
                              onclick: "this.form.submit()",
                              class: "li__input--big",
                              checked: todo.completed %>
          <% end %>

          <% pclass = todo.completed ? "done" : "" %>
          <p class="<%= pclass %>" >

            <%= todo.todo_text %>

          </p>

          <% if show_date %>
            <p class="overdue-dones--info li--date" >

               <%= todo.due_date.to_s(:short) %>

            </p>
          <% end %>

          <a href="#" class="a--hide a__img--trashcan">
            <%= form_with(url: "/todos/#{todo.id}", method: "delete") do |form| %>
              <%= image_submit_tag "trashcan.png",
                          alt: "Delete",
                          onclick: "this.form.submit()" %>
            <% end %>
          </a>
        </li>
      <% end %>
    </ul>
  </section>

app/views/todos/index.html.erb
<main class="body__main--root">
  <h1 class="main__h1--app-head">My Todo-list</h1>
  <%= form_with(url: "/todos", method: "post") do |form| %>
    <%= form.text_field :todo_text,
            class: "input--todo_text",
            placeholder: "What's next?",
            required: true %>
    <%= form.date_field :due_date,
            class: "input--due_date",
            required: true %>
    <%= form.submit :Add,
            class: "btn--pleasant" %>
  <% end %>
  <%= render partial: "todos-section", locals: {
    title: "Overdue",
    todos: @current_user.todos.overdue.completed(false),
    show_date: true
  } %>
  <%= render partial: "todos-section", locals: {
    title: "Due Today",
    todos: @current_user.todos.due_today,
    show_date: false
  } %>
  <%= render partial: "todos-section", locals: {
    title: "Due Later",
    todos: @current_user.todos.due_later,
    show_date: true
  } %>
</main>

app/views/todos/todos.html.erb
<main class="body__main--root">
  <h1 class="main__h1--app-head">My Todo-list</h1>
  <div>
    <input
      type="text"
      name="todo_text"
      id="todo_text"
      class="input--todo_text"
      placeholder="What's next?"
      required
    />
    <input
      type="date"
      name="due_date"
      id="due_date"
      class="input--due_date"
      required
    />
    <input type="button" value="Add" class="btn--pleasant" />
  </div>
  <%= render partial: "todos-section", locals: {
    title: "Overdue",
    todos: Todo.overdue.completed(false),
    show_date: true
  } %>
  <%= render partial: "todos-section", locals: {
    title: "Due Today",
    todos: Todo.due_today,
    show_date: false
  } %>
  <%= render partial: "todos-section", locals: {
    title: "Due Later",
    todos: Todo.due_later,
    show_date: true
  } %>
</main>

app/views/users/new.html.erb
<section class="body__section--root">
  <h1 class="section__h1--app-head"> Welcome new user ! </h1>

  <%= form_with url: users_path do |form| %>
    <div class="form__input--input">
      First Name  :<br/>
      <%= form.text_field :first_name, class: "input__text_field" %>
    </div>
    <div class="form__input--input">
      Last Name :<br/>
      <%= form.text_field :last_name, class: "input__text_field" %>
    </div>
    <div class="form__input--input">
      Email :<br/>
      <%= form.email_field :email, class: "input__text_field" %>
    </div>
    <div class="form__input--input">
      Password :<br/>
      <%= form.password_field :password, class: "input__text_field" %>
    </div>
    <%= form.submit "Sign Up !", class: "sign" %>
  <% end %>
</section>